name: Test Publish to PyPI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade build twine

      - name: Build and publish to PyPI
        env:
          TWINE_USERNAME: __token__            # Always use __token__ for API token auth
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}  # Use your secret here
        run: |
          env | grep TWINE
